"""NIST SP 800-171 Rev 3 pack: pinned OSCAL source, r2->r3 relationships, CCF mappings.

Identifiers and titles come from NIST's OSCAL catalog at a pinned
usnistgov/oscal-content commit; the Rev 2 -> Rev 3 relationships come from
NIST's published change analysis workbook. Both are pinned by sha256 and the
manifest is regenerated by tools/sync_nist_800_171r3.py.
"""

from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

from security_lakehouse.catalog import load_control_catalog, load_framework_registry, validate_catalog
from security_lakehouse.evidence_hints import resolve_connector_hints
from security_lakehouse.framework_packs import (
    PACK_BUILDERS,
    SOURCE_RECONCILED_PACKS,
    nist_800_171_rev3_specs,
    pack_control_row,
    pack_mapping_row,
)
from security_lakehouse.graph import _framework_from_control
from security_lakehouse.mappings import load_control_article_mappings
from security_lakehouse.safeguards import coverage_by_framework, load_safeguards, validate_safeguards

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = json.loads((ROOT / "frameworks/packs/data/nist_800_171_rev3.json").read_text(encoding="utf-8"))
CMMC = json.loads((ROOT / "frameworks/packs/data/cmmc_2_level2.json").read_text(encoding="utf-8"))
FRAMEWORK_ID = "nist-800-171-rev3"
PREFIX = "NIST-800-171R3-"
OSCAL_COMMIT = "78650f02ad9321bb7b817846f8fbd4f2bcd620de"

FAMILY_COUNTS = {
    "03.01": 16,
    "03.02": 2,
    "03.03": 8,
    "03.04": 10,
    "03.05": 8,
    "03.06": 5,
    "03.07": 3,
    "03.08": 7,
    "03.09": 2,
    "03.10": 5,
    "03.11": 3,
    "03.12": 4,
    "03.13": 10,
    "03.14": 5,
    "03.15": 3,
    "03.16": 3,
    "03.17": 3,
}

# Requirements with no honest CCF home today. "lane" means the only safeguard
# that carries the Rev 2 predecessor is a narrow, test-pinned crosswalk lane.
UNMAPPED = {
    "03.01.04": "lane",
    "03.01.08": "lane",
    "03.01.09": "lane",
    "03.01.22": "no-home",
    "03.04.08": "lane",
    "03.07.06": "no-home",
    "03.09.02": "lane",
    "03.10.06": "lane",
    "03.13.04": "lane",
    "03.13.12": "no-home",
    "03.13.13": "no-home",
    "03.14.02": "lane",
}


def _controls() -> dict[str, dict]:
    return {cid: row for cid, row in load_control_catalog().items() if row["framework_id"] == FRAMEWORK_ID}


def _members() -> list[tuple[str, dict]]:
    return [
        (entry["safeguard_id"], member)
        for entry in load_safeguards()["safeguards"]
        for member in entry["satisfies"]
        if member["framework_id"] == FRAMEWORK_ID
    ]


def test_manifest_is_every_active_rev3_requirement() -> None:
    ids = [row["id"] for row in MANIFEST["rows"]]
    assert len(ids) == len(set(ids)) == 97
    assert all(re.fullmatch(r"03\.\d{2}\.\d{2}", i) for i in ids)
    assert Counter(row["family"] for row in MANIFEST["rows"]) == FAMILY_COUNTS
    assert set(MANIFEST["families"]) == set(FAMILY_COUNTS)
    for row in MANIFEST["rows"]:
        assert 0 < len(row["title"]) <= 80, row["id"]
        assert row["id"].startswith(row["family"] + ".")


def test_sources_are_pinned() -> None:
    source = MANIFEST["source"]
    assert source["oscal_commit"] == OSCAL_COMMIT
    for key in ("catalog_sha256", "pdf_sha256"):
        assert re.fullmatch(r"[0-9a-f]{64}", source[key]), key
    assert source["pdf"] == "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-171r3.pdf"
    analysis = source["r2_r3_analysis"]
    assert analysis["url"].startswith("https://csrc.nist.gov/files/pubs/sp/800/171/r3/final/docs/")
    assert re.fullmatch(r"[0-9a-f]{64}", analysis["sha256"])
    registry = load_framework_registry()[FRAMEWORK_ID]
    assert registry["source_sha256"] == source["catalog_sha256"]
    assert registry["pulled_at"] == source["pulled_at"]
    assert registry["implementation_status"] == "implemented_limited_mapping"
    assert registry["official_source_url"] == "https://csrc.nist.gov/pubs/sp/800/171/r3/final"


def test_r2_relationships_only_cite_real_rev2_requirements() -> None:
    """Every Rev 2 -> Rev 3 link comes from NIST's analysis and names a real Rev 2 id."""
    r2_ids = {row["id"] for row in CMMC["requirements"]}
    accounted: set[str] = set()
    for row in MANIFEST["rows"]:
        for link in row["r2_predecessors"]:
            assert link["id"] in r2_ids, (row["id"], link)
            assert link["relationship"] in {"carried_forward", "incorporated_into"}
            accounted.add(link["id"])
    for entry in MANIFEST["r2_not_carried"]:
        assert entry["id"] in r2_ids
        assert entry["reason"]
        accounted.add(entry["id"])
    # All 110 Rev 2 requirements are accounted for, once as a predecessor or a withdrawal.
    assert accounted == r2_ids
    anomalies = MANIFEST["source_anomalies"]
    assert [a["analysis_r2_id"] for a in anomalies] == ["3.11.4"]


def test_new_rev3_requirements_have_no_predecessor() -> None:
    new = {row["id"] for row in MANIFEST["rows"] if not row["r2_predecessors"]}
    assert new == {
        "03.04.10",
        "03.04.11",
        "03.04.12",
        "03.05.12",
        "03.06.04",
        "03.06.05",
        "03.10.08",
        "03.11.04",
        "03.12.05",
        "03.14.08",
        "03.15.01",
        "03.15.03",
        "03.16.01",
        "03.16.02",
        "03.16.03",
        "03.17.01",
        "03.17.02",
        "03.17.03",
    }


def test_catalog_rows_are_generated_from_the_builder() -> None:
    controls = _controls()
    specs = nist_800_171_rev3_specs()
    assert [s.article_id for s in specs] == [row["id"] for row in MANIFEST["rows"]]
    assert set(controls) == {PREFIX + row["id"] for row in MANIFEST["rows"]}
    mappings = load_control_article_mappings()
    for spec in specs:
        assert controls[spec.control_id] == pack_control_row(spec)
        assert mappings[spec.control_id] == pack_mapping_row(spec)
    assert "nist-800-171-rev3" in PACK_BUILDERS
    assert validate_catalog() == []


def test_review_state_is_honest() -> None:
    assert SOURCE_RECONCILED_PACKS[FRAMEWORK_ID] == MANIFEST["source"]["pulled_at"]
    for control in _controls().values():
        assert control["review_status"] == "proposed"
        assert control["source_reconciled_by"] == "automated-source-reconciliation"
        assert control["framework_ref"].startswith("NIST SP 800-171 Rev 3 03.")


def test_cmmc_stays_on_rev2() -> None:
    cmmc = [row for row in load_control_catalog().values() if row["framework_id"] == "cmmc-2-level2"]
    assert len(cmmc) == 110
    assert all(row["framework_ref"].startswith("NIST SP 800-171 Rev 2 ") for row in cmmc)


def test_every_control_has_evidence_types_and_hints() -> None:
    for control_id, control in _controls().items():
        assert control["required_evidence_types"], control_id
        article_id = control_id.removeprefix(PREFIX)
        hints = resolve_connector_hints(framework_id=FRAMEWORK_ID, control=control, article_ids=[article_id])
        assert hints and hints[0]["priority"] == "primary", control_id
        assert _framework_from_control(control_id) == FRAMEWORK_ID


def test_safeguard_mappings_are_proposed_cited_and_leave_lanes_alone() -> None:
    payload = load_safeguards()
    assert validate_safeguards(payload) == []
    pdf = MANIFEST["source"]["pdf"]
    analysis = MANIFEST["source"]["r2_r3_analysis"]
    rows = {row["id"]: row for row in MANIFEST["rows"]}
    lanes = {entry["safeguard_id"] for entry in payload["safeguards"] if "mapping_source" in entry}
    for sid, member in _members():
        assert sid not in lanes, (sid, member["control_id"])
        assert member["review_status"] == "proposed"
        expected_role = (
            "primary" if sid in {"SG-INFORMATIONEXCHANGE-001", "SG-PERSONNELSCREENING-001"} else "equivalent"
        )
        assert member["role"] == expected_role
        assert "review_basis" not in member
        source = member["mapping_source"]
        requirement = member["control_id"].removeprefix(PREFIX)
        if source["url"] == analysis["url"]:
            assert source["sha256"] == analysis["sha256"]
            predecessor = re.search(r"Rev 2 (3\.\d+\.\d+) ", source["locator"]).group(1)
            assert predecessor in {p["id"] for p in rows[requirement]["r2_predecessors"]}
            assert f"Rev 3 {requirement}" in source["locator"]
        else:
            assert source["url"] == pdf
            assert source["sha256"] == MANIFEST["source"]["pdf_sha256"]
            assert source["locator"].endswith(f"requirement {requirement}")


def test_unmapped_requirements_are_exactly_the_documented_gaps() -> None:
    mapped = {member["control_id"].removeprefix(PREFIX) for _, member in _members()}
    assert set(rows := {row["id"] for row in MANIFEST["rows"]}) - mapped == set(UNMAPPED)
    assert mapped <= rows
    gaps = {gap["id"]: gap for gap in MANIFEST["unmapped"]}
    assert set(gaps) == set(UNMAPPED)
    for requirement, reason in UNMAPPED.items():
        assert gaps[requirement]["reason"], requirement
        if reason == "lane":
            assert "lane" in gaps[requirement]["reason"]
    coverage = coverage_by_framework()["frameworks"][FRAMEWORK_ID]
    assert coverage["controls"] == 97
    assert coverage["covered"] == 97 - len(UNMAPPED)
    assert coverage["maintainer_reviewed"] == coverage["org_reviewed"] == 0


def test_sync_tool_reproduces_the_manifest_offline(tmp_path: Path) -> None:
    sys.path.insert(0, str(ROOT / "tools"))
    import sync_nist_800_171r3 as tool

    assert tool.OSCAL_COMMIT == OSCAL_COMMIT
    rows = tool.parse_analysis_rows(tool.read_xlsx_rows(_tiny_workbook(tmp_path)))
    assert rows[0]["r2"] == "3.1.1" and rows[0]["r3"] == "03.01.01"
    assert rows[1]["withdrawn_text"] == "Incorporated into 03.01.12."


def _tiny_workbook(tmp_path: Path) -> Path:
    """A two-row xlsx in the analysis layout, built with the stdlib only."""
    import zipfile

    header = [
        "Family",
        "R2 SORT-ID",
        "R2 Identifier",
        "R2 Requirement",
        "Basic or Derived",
        "R3 SORT-ID",
        "R3 Identifier",
        "Requirement Name",
        "R3 Requirement",
        "No Significant Change",
        "Significant Change",
        "Minor Change",
        "New ODP",
        "New Requirement",
        "Withdrawn Requirement",
        "Summary",
    ]
    data = [
        header,
        ["Access Control", "R2-03-01-01", "3.1.1", "x", "Basic", "R3-03-01-01", "03.01.01", "Account Management"]
        + ["y", "", "X", "", "X", "", "", "s"],
        ["Access Control", "R2-03-01-13", "3.1.13", "x", "Derived", "R3-03-01-13", "03.01.13", "Withdrawn"]
        + ["Incorporated into 03.01.12.", "", "", "", "", "", "X", ""],
    ]

    def cell(ref: str, value: str) -> str:
        return f'<c r="{ref}" t="inlineStr"><is><t>{value}</t></is></c>' if value else ""

    letters = "ABCDEFGHIJKLMNOP"
    sheet_rows = "".join(
        f'<row r="{r + 1}">' + "".join(cell(f"{letters[c]}{r + 1}", v) for c, v in enumerate(row)) + "</row>"
        for r, row in enumerate(data)
    )
    path = tmp_path / "analysis.xlsx"
    ns = 'xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"'
    rel_ns = 'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"'
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr(
            "xl/workbook.xml",
            f'<workbook {ns} {rel_ns}><sheets><sheet name="{tool_sheet()}" sheetId="1" r:id="rId1"/></sheets></workbook>',
        )
        archive.writestr(
            "xl/_rels/workbook.xml.rels",
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            '<Relationship Id="rId1" Target="worksheets/sheet1.xml" '
            'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet"/></Relationships>',
        )
        archive.writestr("xl/worksheets/sheet1.xml", f"<worksheet {ns}><sheetData>{sheet_rows}</sheetData></worksheet>")
    return path


def tool_sheet() -> str:
    import sync_nist_800_171r3 as tool

    return tool.ANALYSIS_SHEET
