-- GRC Lake Snowflake evidence-lake POC bootstrap.
--
-- Run from a Snowflake role allowed to create a database, warehouse, role, and
-- grants. The script creates only GRC Lake-owned objects and a read-only role.
-- It does not create users, passwords, integrations, stages, or external
-- network access.
--
-- Default objects:
--   database:  GRC_LAKE_SECURITY_LAKE
--   schema:    GRC_LAKE_SECURITY_LAKE.EVIDENCE
--   warehouse: GRC_LAKE_READ_WH
--   read role: GRC_LAKE_READER
--
-- The secure views read SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY so a first POC can
-- prove existing-lake collection without loading customer data into GRC Lake.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS GRC_LAKE_READER;

CREATE WAREHOUSE IF NOT EXISTS GRC_LAKE_READ_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Read-only GRC Lake POC warehouse';

CREATE DATABASE IF NOT EXISTS GRC_LAKE_SECURITY_LAKE
  COMMENT = 'GRC Lake governed evidence lake POC';

CREATE SCHEMA IF NOT EXISTS GRC_LAKE_SECURITY_LAKE.EVIDENCE
  COMMENT = 'Curated read-only evidence views for GRC Lake';

SET GRC_LAKE_POC_USER = CURRENT_USER();

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE GRC_LAKE_READER;
GRANT USAGE ON WAREHOUSE GRC_LAKE_READ_WH TO ROLE GRC_LAKE_READER;
GRANT USAGE ON DATABASE GRC_LAKE_SECURITY_LAKE TO ROLE GRC_LAKE_READER;
GRANT USAGE ON SCHEMA GRC_LAKE_SECURITY_LAKE.EVIDENCE TO ROLE GRC_LAKE_READER;
GRANT ROLE GRC_LAKE_READER TO USER IDENTIFIER($GRC_LAKE_POC_USER);

CREATE OR REPLACE SECURE VIEW GRC_LAKE_SECURITY_LAKE.EVIDENCE.GRC_LAKE_AUDIT_EVENTS AS
SELECT
  QUERY_ID AS audit_id,
  USER_NAME AS actor,
  COALESCE(DATABASE_NAME || '.' || SCHEMA_NAME, DATABASE_NAME, WAREHOUSE_NAME, 'snowflake') AS object_name,
  CASE WHEN EXECUTION_STATUS = 'SUCCESS' THEN 'observed' ELSE 'open' END AS status,
  CASE WHEN EXECUTION_STATUS = 'SUCCESS' THEN 'info' ELSE 'medium' END AS severity,
  QUERY_ID AS evidence_ref,
  QUERY_ID AS query_id,
  QUERY_TYPE AS event_action
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP());

CREATE OR REPLACE SECURE VIEW GRC_LAKE_SECURITY_LAKE.EVIDENCE.GRC_LAKE_CONTROL_POSTURE AS
SELECT
  'SNOWFLAKE-AUDIT-QUERY-LOGGING' AS control_id,
  CASE WHEN COUNT(*) > 0 THEN 'passed' ELSE 'open' END AS status,
  CASE WHEN COUNT(*) > 0 THEN 10 ELSE 70 END AS risk_score,
  CASE WHEN COUNT(*) > 0 THEN 'low' ELSE 'high' END AS severity,
  'snowflake-query-history' AS evidence_ref,
  'SOC2' AS framework_id,
  0.95 AS confidence
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
UNION ALL
SELECT
  'SNOWFLAKE-FAILED-QUERY-REVIEW' AS control_id,
  CASE WHEN COUNT_IF(EXECUTION_STATUS <> 'SUCCESS') = 0 THEN 'passed' ELSE 'open' END AS status,
  CASE WHEN COUNT_IF(EXECUTION_STATUS <> 'SUCCESS') = 0 THEN 10 ELSE 60 END AS risk_score,
  CASE WHEN COUNT_IF(EXECUTION_STATUS <> 'SUCCESS') = 0 THEN 'low' ELSE 'medium' END AS severity,
  'snowflake-query-failures' AS evidence_ref,
  'SOC2' AS framework_id,
  0.85 AS confidence
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP());

CREATE OR REPLACE SECURE VIEW GRC_LAKE_SECURITY_LAKE.EVIDENCE.GRC_LAKE_ASSET_RISK AS
SELECT
  'snowflake:warehouse:' || LOWER(COALESCE(WAREHOUSE_NAME, 'unknown')) AS asset_id,
  'warehouse' AS asset_type,
  'snowflake' AS owner,
  'prod' AS environment,
  CASE WHEN COUNT_IF(EXECUTION_STATUS <> 'SUCCESS') > 0 THEN 60 ELSE 10 END AS risk_score,
  CASE WHEN COUNT_IF(EXECUTION_STATUS <> 'SUCCESS') > 0 THEN 'open' ELSE 'observed' END AS status,
  CASE WHEN COUNT_IF(EXECUTION_STATUS <> 'SUCCESS') > 0 THEN 'medium' ELSE 'low' END AS severity,
  'snowflake-warehouse-' || LOWER(COALESCE(WAREHOUSE_NAME, 'unknown')) AS evidence_ref
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY COALESCE(WAREHOUSE_NAME, 'unknown');

CREATE OR REPLACE SECURE VIEW GRC_LAKE_SECURITY_LAKE.EVIDENCE.GRC_LAKE_EVIDENCE_BUNDLES AS
SELECT
  QUERY_ID AS bundle_id,
  QUERY_ID AS evidence_ref,
  CASE WHEN EXECUTION_STATUS = 'SUCCESS' THEN 'observed' ELSE 'open' END AS status,
  CASE WHEN EXECUTION_STATUS = 'SUCCESS' THEN 'info' ELSE 'medium' END AS severity,
  SHA2(QUERY_ID || ':' || COALESCE(QUERY_TEXT, ''), 256) AS hash_sha256,
  'snowflake://account_usage/query_history/' || QUERY_ID AS object_uri
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP());

GRANT SELECT ON VIEW GRC_LAKE_SECURITY_LAKE.EVIDENCE.GRC_LAKE_AUDIT_EVENTS TO ROLE GRC_LAKE_READER;
GRANT SELECT ON VIEW GRC_LAKE_SECURITY_LAKE.EVIDENCE.GRC_LAKE_CONTROL_POSTURE TO ROLE GRC_LAKE_READER;
GRANT SELECT ON VIEW GRC_LAKE_SECURITY_LAKE.EVIDENCE.GRC_LAKE_ASSET_RISK TO ROLE GRC_LAKE_READER;
GRANT SELECT ON VIEW GRC_LAKE_SECURITY_LAKE.EVIDENCE.GRC_LAKE_EVIDENCE_BUNDLES TO ROLE GRC_LAKE_READER;

-- Validation: run after the grants above. Every query should return one row.
USE ROLE GRC_LAKE_READER;
USE WAREHOUSE GRC_LAKE_READ_WH;
USE DATABASE GRC_LAKE_SECURITY_LAKE;
USE SCHEMA EVIDENCE;

SELECT COUNT(*) AS audit_events FROM GRC_LAKE_AUDIT_EVENTS;
SELECT COUNT(*) AS control_posture FROM GRC_LAKE_CONTROL_POSTURE;
SELECT COUNT(*) AS asset_risk FROM GRC_LAKE_ASSET_RISK;
SELECT COUNT(*) AS evidence_bundles FROM GRC_LAKE_EVIDENCE_BUNDLES;
